env:
  global:
    # DOCKER_EMAIL
    - secure: "qokEL3Dg12uIT5EM9wRXTfSwebc0eaKMB0uedYKF3XttJjHgkwQ8zsYd23HG0jnt8InDUzLhWekQzZW5Q1BTQc8aMQz+V2J8WIAXJmdMwcEXCuyyWtOwoMGm+JMKOWvwH04gos5YBQK7XkKd5uvLWo1A+9ok0CX71vARewQ42V1/SA/EmaQQa4MZ1fcE2+mNidGw2ONEwzp1N8DFnw1NMrt8bP9bYYSdUgW99/5hzg6RHR9kZnFPKhCeMtm7pNaPn2k6w7xg7nVpKJchqa93W42zYb40OpqiQ6H9wW44yN9yZkIuHZA7U6rdH1xJOpjXyACTeqdoxtgS4EcSGXxt2cPSq8gaBUNHx8Cpyb7nHqpi4/DWUBFtPO70fWv1ZxIx/pRXZ0Slpr+ANWrlipyYOtPzPiqqJSGEeXsXKWZykp0GhWTLS8Pe4FbhoPPcYq8JGibPPKHfenswHKGI9MiSbjXWJt25N4k4LaE45lR61m4f4HhNT6R0qlWIAgC6eo7xqtbaU6KymBWmuDGAwV66MV3f6dd/RLZvM3k04OZynE6WmYEhEvHsfQ/BKF67MbF8Jjk2bz+a3XHPoLaODpsGP+dJylrc5Ci6aJwukfxYvjHsTxX+NgemMihlhThydXEOc2z3Ye/D7tGvVzkvh6cWx2+s+3xId3Mr9fe9f7IWEkE="
    # DOCKER_USER
    - secure: "RI+qFojXg8Yb3sVJABZTBo90Z8F/JjC8B6WBO/1P+2vkUfKkhdnrAzePoMheWFXfLuGdAYpgWfCUM6NY4WGdEnC4dR4NxjdpNXoscHPOWUDe2NgbKCop8jOJ9lksnuhmHpMFNo5zQshCfsPNBEIURiemg16tIJ1DtBNaWs4Xgm7lmV5rQ1Ucz6cddCw8FCIduULbgUbPBtiuLiQ3ExZW+spdP9iRvZUiXDA8qoCCFAzm6sjPYcS8EbryCnRlu1zu4Rr4m+9DUvcs9Rwbd+g9XvWUh0Be1dKRYHMzTgvZjdnV5WtO+TGIQuPb97u19nL9w8CNaqpev4XzoXpiDTmKA4GIXmZNPsiLUoaTtwXXC+GdBM2J2qfjQ+9kIBXGdp2BDIdI9haC04URA+EkoYB5HtIRq8qbRbtfQg/Vtn2MLZKQ3ndgNSI7Y+Q3n1VyGuhMtFyBz975jBm1QgmsxyHrxUPtXCliGJHVu3dCpU9OK5Fv3fttop5YpVy8bF2WB1C9RoN5fK105B6yowHeU96ckw99baI2c1Z1MiRw9er+ogs2Ii+v6GuGkB76BtkudcsHVz2PP3kysNcveowmk8y+P6Z2+TsH5yvOu9mxZRGp/Im48W48uTnmg6RxWjh26ZfOD+Mts19YhTQWyVGATozpYAPrgeJyGvThkBFa7w+9TEc="
    # DOCKER_PASS
    - secure: "S4ge+eD5ywmFIhgmKSiRPJWtjCNBZ14vG5yJM1bEOGpfeK/04TRAP2/Bwf2yyHxf/pJI0LYJp909MQWSqjOYP168unhvmQWn6GopnZ2GUqQzKTGKk9xv1Jn2acevmJigsPpvHrx2a3FsEg1HPejjrR1FIlZQhSYQEFBiSwEiwpgaM5EFLSNwYtlB372M6czJxdiClxXOuzRaTrIRr7p7yem0kEn1pCAxlHH5y9UsPn1s40gyGLp6XPDeZHxXcJuJOHmS9Eb4CwWqKnNCuDBMafCv0CS5qvrlK2Kn2ep+p/W5tXQ/HlbAzppernTN2ErgF/I5QdUR1ua7BxaSDsDQNdRC4iZ77P6GrImyjKAWTw0ikORxGYqhQ0Z5AsmCEcgS446s29L82owx/ft/f24eS+dN30J7awduryOAEWnooqE85RIVrvRIWlsiJ07go+COWUZyQWew3YTuWKaE/huTl+P+j3uGAfL+4uo57tAMR3LE60n9vbJlfOhLY9lqAV75E6UIRdGiOH93vfzmntuBoTSrSsktSdxP43u8hA6bQ2RFItry6c5FckSstKAFLQu2yFTOk4WRYzzCXQMtI92pABNRZOyosOGQw+pIh+LVZ5WSppFXGy90+pmp/8Jq+86h4qyCJ0cNZ3C1xextCkbdd7Ssw5bpTr4TEJvABJPxFs8="
    # GITHUB_TOKEN
    - secure: "XwPnGr4C5U6cokWxs4jkzLymHKzK4BeEM+IK224hJzva91v70VGolcVOXQreW8fnJWbSAUMhWJZZDOQXePj4XoRAB+Zcds9o3ljK1H6lnuFPvQLD1c0AZoxmAcysH1CjgMT+vUbi3EViOYJCfzgkVTskBiiGI+r4T3ZAXbcaOMokM1PERXg8WrFfPLc07BD42vNlmJeXd5ggbG0B2aHrD8QFrMAk9+QCeYj+6ANk0vO+/diXhnnARY96+/lrZiiKVNjpb3TiMh1xIyu2EJl+TZddncLRjDZRZIgqCEhCW4D4BP/6XbI5kKK98vm34RelM9wRTPTp2nOLiHS1W44Jh8Bf8F6i49p4wQF2i+pPXEMR7HOZjYE2iAUG6C7B20xTPWF51iKsHCDm2xM0RduDxQAvcTTiFO2K/FLR2XYAyS39+JQajOp20m9Vw/4A8LJjfBmSwGcI8JDv0rbDHuUTjlvC98O24Vu+8lUKaysysS1AtIdLEpWMpdzPDwXtAIpHuMTQ9LAszWPEYeDajazuD6EbkOybjVXUmJnsIu1JGzeYwVpI7lblwhD5/4lt70MjEjEQBBcDN9yGdBYfu7jDuwMB1bDsHw1Fp6kU2aUOnpRn0Q9Biw7FyC2sC0+v0ErCS7w+d3hVQRyhAJQy8fTBopB+3KJc/Wb/SRwLZZ/JhZM="

language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules

sudo: required
services:
  - docker

install:
  - npm i

script:
  - npm run lint
  - npm run build
  - docker-compose pull
  - NO_UI=true docker-compose up -d
  - sleep 15
  - npm test

after_success:
  # No docker push on pull requests
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit; fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=koumoul/data-fair
  # Pull before push in order to fill docker cache
  - docker pull $REPO:master
  - docker build -f Dockerfile --cache-from $REPO:master --build-arg VERSION=$TRAVIS_BUILD_NUMBER -t $REPO:$TRAVIS_BRANCH .
  - docker push $REPO:$TRAVIS_BRANCH
  # Doc build
  - npm run build-doc
  # The following is only for tags
  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
  # create alternative tags for the docker image
  - docker tag $REPO:$TRAVIS_TAG $REPO:latest
  - docker push $REPO:latest
  - export MAJOR=$(./node_modules/.bin/semver-extract --major $TRAVIS_TAG)
  - docker tag $REPO:$TRAVIS_TAG $REPO:$MAJOR
  - docker push $REPO:$MAJOR
  - export MINOR=$(./node_modules/.bin/semver-extract --minor $TRAVIS_TAG)
  - docker tag $REPO:$TRAVIS_TAG $REPO:$MINOR
  - docker push $REPO:$MINOR
