env:
  global:
    # DOCKER_USER
    secure: "BZcfF2ITZRNGWurUnE1RB2/fJnu1yW07qZWfuXCcTz/hc2BvUhvDihPB5RjBXcxUobwtVWRQcnE/3LdgJbVeKVAAkrV3Exz0IatLXT8YlrIQdiLf88M78WUU+WIVwShydci0WQwA3zDuOih9z4Zn8f0UhrEEslwhrkEnEfoTHIOakO1c6nv9zql/Fq/WfDB3z1D9aFBh/6lsJ7PBJnhELBM1+X4o5V+QXZ+sSw4JTiQCe5aZRVRKVaKDXwN2Lzs9dWTphWztFGJ9i1aem/96ugnPyYbnqLa7rWvC4rJVy36IFRkxAficoubsOAjoxDX3RFq84QBjnqrLG5EQDX42dLkBtWRuXMsUtGFZNXqRw9Nq/SpDUYfrlDQLw8+btSpJjIyhD0NRHwkmCDi0JIJmzhFdZzD3DyZfF2OhJYHEipbLMdDcSaYNhfPzrTmjpCa3ke5fND7XyS86l9K9zEVTZsSvAj29XbXwpX4N55YmTWhLDp8RHejfDoSLQULQ8hR1TN2HDCq4uJjWzY3d6Ds+MDE4hEmFfxqSOhsuSl+Z5uFsOdBji1cVmvdGTU6PPPlGgkbFFjQD7x8vtUu2aGsLgN/s0V9qOemYHz1QzFvtXUiu35TIImkn1GXeDSxmyEI4bz1ocYT7fHYeRsWJVYDp5gxH96pl/xH/ViRujV0paUo="
    # DOCKER_PASS
    secure: "lUuuwJZEHJrgjMu8L3QT3wTkJufvf92jdanM6lewib0UxpETY2/GlRQjy4gvdvGMfB3H53osuUnxSmXF8R1abOC7PpaxZahkw+COmidnOVFC/ShzXc1dwnXWyxmGYBFoZHbbzxlQwkQx+ILNxeUMqZ72zGO2armOQh5FWLjOPi9RxRzcwFtP/B1dxCa7jy5H4Xa6p7bTHRkVvNuIHQVXFG3xmcZXB/6+2hHvsFd113glKSZ773KzsDYoq99s1dNSqw1QyvLBOs4ovtX811G/1LgHIKrfDGUMjjtsQZhRJzzpk69aN56t7usfMbJYeKMv62CtKlKwQ4BPNtNBqwWrSoX3MADultq8J8mEjkOLtJ5RAZtleTBPJmlVNyFR6QmiHH9FAVohTTuPlg1OFpQMAGdA1RbeHbDS01W3YUeg+5fWzBlcpAX7Ij2MwYZiw8J4nV2JX2WNm83kPrUx9CGvhP/1i7u2mdyrW8KBc0kO610+Er5kAhtmBuGYpiK9Qwc1w1stcmnGJzWOEhKhWx44CWaNDvFAt83LOo1kk9Ibspwu1f58W0OKTGyxGojsL9Pozo0TiSZo1MVSGDgs2qapaMbqe7ZPBrJrKwUbBYK5FaFWDHYgnrhbo3a4a6GWPHqTGutkqzIq3g4bHiHXyqP2mK0lKR78o7Qk/6QGa+TrQhM="

language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
sudo: required
services:
- docker
install:
- npm i
script:
- npm run lint
- npm run build
#- docker-compose pull
#- NO_UI=true docker-compose up -d
#- sleep 15
#- npm test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit; fi
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=koumoul/notify
- docker pull $REPO:master
- docker build -f Dockerfile --cache-from $REPO:master --build-arg VERSION=$TRAVIS_BUILD_NUMBER
  -t $REPO:$TRAVIS_BRANCH .
- docker push $REPO:$TRAVIS_BRANCH
- npm run build-doc
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker tag $REPO:$TRAVIS_TAG $REPO:latest
- docker push $REPO:latest
- export MAJOR=$(./node_modules/.bin/semver-extract --major $TRAVIS_TAG)
- docker tag $REPO:$TRAVIS_TAG $REPO:$MAJOR
- docker push $REPO:$MAJOR
- export MINOR=$(./node_modules/.bin/semver-extract --minor $TRAVIS_TAG)
- docker tag $REPO:$TRAVIS_TAG $REPO:$MINOR
- docker push $REPO:$MINOR
