env:
  global:
    # DOCKER_USER
    secure: "DuwzHKnZDDlZZAPkNru98PQFNYb7tzE0x1qPUwvgS5mPiRq8ljvlUX/LJqzz+vGF3qAlWoaY1mk2KFyH2OTFVWGFHMEAbYXJxCKtmGD5jGRQWcTPsDqPeabOZZHYPqgC3wroPpPeI4wytCz/yiodQzI9n3dlvjGUK0SwparRbwX9O6rJRkdn4TOe4wRrAzvnWo/3JGQ6FbNV0luLmwI0litx49tqi4Owu5rvombxTi69oNueuoeqnYPinGRoaalegdewfr5LaI0K7Tx0Cjso1KBPmxS+wkGjvOj2/oDz9t/IYq/Ryt2lWcLOHQLvTBplFWJ/aWsghky1ruB0Sc4FHalHiA5XWvQjjrAQ/5lUCEE7ysn7XTm6IugTUmLG211WEvrM14WKKjcicTE91NexzmSL74yoP2nW+xVNGQjHDqmPwnoGn26ZUxARG5uQ9gBUqcO/ahFvCl81PoaDEXzwaa+G5qeLQUzOaVAgRaFDFVebOCNpFbyYy0kHVRjQ7jEBoOIp7YA0gqpXLPNvFJWfgP2/h2iwnL6JFZKR9s+g5QOgiNvcfCbHv68XmyKAKH4sPo18q6qpSgOKqCK/gKk8cEJIfo+Zud2d+iLI4r/OmpzxxAbbVaXwFSCbkl8qM58Xg0M6ZmUg+LpHupzdgAWFQIUjy0lIZ+ZEgEnKz7rR1TU="
    # DOCKER_PASS
    secure: "3yX1H/jsEv8smg9Tkc1IcREiZHWZfP3bRuCbQP+QieCV904q8ggIWMtcO8EUy56cKEYO3vcbtwBm4DZX38nzS3FyyZVZRkXm6VYOzzhqq7wChHTvdFL2fT/5c8hPaE2bHPoIEqeFwDGj5oN1b7c5PjGZPnFpfmiZh/H+A2tXD91hRRaWNp3EVUtu+Vb9yhq8D/RwA/jdLY1VvwOOF7AmwFVM7KCabYMo/3l3uZvuMsCSBmzUwB2K2jGJrZNZcsVbsaicovD9wksAK4oFzhfrBEghFWEDJO4nCJ1QABfM3lDq63ZMjlFCMSt7TI/JrPnRN135awUCMfGVeZ7V7o6/UilS7+fwJRaj/Vtp8Lqak6UjRgpN6hhlTXT/e0x/znMUNy8XesdQ+TyyHpOPeSoXhNq6CMZEfqtzt+18+ybOaMuwfHMoO8PkkygOFawf49uIDU2M+5MuUAwizWAy49gfpUWXtemD2biH+tLCxBfyl0uCnawqp9xhcusxPUEthIigY2FgjjCD+jDTOnTvkHfQsTv66wnVR1S6X2iraZxdzTklih0ejpTcohKKI1wjBTqKdh19OuGeicop/fIDRo4+K5aAGphsJqoyohxa5AozZkIq/AGGzGDiGWRWXehXzszkwPRZWi0KRWHGGY0soz63zfWvsTeah6+iGfZp5vBl6cg="

language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
sudo: required
services:
- docker
install:
- npm i
script:
- npm run lint
- npm run build
- docker-compose pull
- NO_UI=true docker-compose up -d
- sleep 15
- npm test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit; fi
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=koumoul/data-fair
- docker pull $REPO:master
- docker build -f Dockerfile --cache-from $REPO:master --build-arg VERSION=$TRAVIS_BUILD_NUMBER
  -t $REPO:$TRAVIS_BRANCH .
- docker push $REPO:$TRAVIS_BRANCH
- npm run build-doc
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker tag $REPO:$TRAVIS_TAG $REPO:latest
- docker push $REPO:latest
- export MAJOR=$(./node_modules/.bin/semver-extract --major $TRAVIS_TAG)
- docker tag $REPO:$TRAVIS_TAG $REPO:$MAJOR
- docker push $REPO:$MAJOR
- export MINOR=$(./node_modules/.bin/semver-extract --minor $TRAVIS_TAG)
- docker tag $REPO:$TRAVIS_TAG $REPO:$MINOR
- docker push $REPO:$MINOR
