version: '3'
services:
  sd:
    profiles:
      - dev
      - test
    image: koumoul/simple-directory:master
    network_mode: host
    environment:
      - DEBUG=webhooks
      - ADMINS=["superadmin@test.com"]
      - PUBLIC_URL=http://localhost:5994/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - NUXT_BUILD_BLOCKING=false
      - NO_UI=${NO_UI}
      - SECRET_SENDMAILS=sendmails-secret
      - AUTHRATELIMIT_ATTEMPTS=200
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  openapi-viewer:
    profiles:
      - dev
    image: koumoul/openapi-viewer:1
    ports:
      - 5680:8080

  mongo:
    profiles:
      - dev
      - test
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: